spring.application.name=spring_demo
server.port = 1237

spring.datasource.url=jdbc:mysql://localhost:3306/sample_rest_api?createDatabaseIfNotExist=true
<<<<<<< HEAD
spring.datasource.username=${DB_USERKNAME}
=======
spring.datasource.username=${DB_USERNAME}
>>>>>>> bd29264a924a74ed1dd2a7a35660f5c221bbbe76
spring.datasource.password=${DB_PASSWORD}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
